lexik_jwt_authentication:
    secret_key:  '%kernel.project_dir%/config/jwt/private.pem'
    public_key:  '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl:   43200

    token_extractors:
        authorization_header:
            enabled: false
        cookie:
            enabled: true
            name:    AUTH_TOKEN

    set_cookies:
        AUTH_TOKEN:
            lifetime: null
            samesite: lax
            path: '/'
            domain: null
            secure: true
            httpOnly: true
